### ISSUE TITLE
Так что именно делает ваша библиотека и главное зачем?

### ISSUE THREAD

**Issue by acwartz** [parimatch-tech/midmare#47]
Сабж, статья на хабре не ответила на этот вопрос, кроме очевидного: как установить npm пакет и как это подключить.
Тащить легаси-код? Вкуда?

Читнув код вижу что это вполне себе ручной такой маршрутизатор который куда-то ведет если очень надо даже там где маршрутизацию не завезли, а http не положен. Не хватает инфы и примеров использования (там где веб не нужен, а лучше конкретного примера того для чего вы решили тащить легаси этим а не избавится от него).

**Comment by W0LFMAN** [comment]
@acwartz 
Тащить легаси код? Моя идея не тащить легаси, а полностью избавиться от него переписав реализацию на более поддерживаемую и читабельную. Как я вам уже отписал в комментариях, я попробую сделать демку возможностей в ближайшее время чтобы пользователям было понятно. Спасибо вам за ваши замечания.
